# .readthedocs.yaml
# Read the Docs configuration file (v2)
# Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - gmt  # Installs GMT 6.0.0 (default for Ubuntu 20.04)

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Install Python dependencies for building docs
python:
  install:
    - requirements: docs/requirements.txt
