# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - gmt  # Install GMT 6.0+ from Ubuntu repositories
  env:
    GMT_VERSION: "6.0.0"

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Install Python dependencies for building docs
python:
  install:
    - requirements: docs/requirements.txt
